config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'pages#home'

  get 'about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # To support Devise for User management
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Routes for Rooms
  resources :rooms do
    resources :messages
  end

  get 'roomslist', to: 'rooms#list'
  get 'rooms_admin', to: 'rooms#admin'

  # Custom routes for users
  get 'user/:id', to: 'users#show', as: 'user'
end

app/views/pages/about.html.erb
<h4 class="text-center mt-2">About TurboChat</h4>
<div class="container-sm text-left col-6">
  TurboChat was written (well...okay - <strong>transcribed</strong>) while following along with this tutorial from Deanin: <a href="https://www.youtube.com/watch?v=UvTLumcEMgU"><em>Realtime Chat App With Ruby On Rails 7, Turbo, and Electron</em></a> by this old guy:<br>
  <div class="container text-center mt-2 mb-4">
    <%= avatar_for_name('David Peloso', size:('200x200')) %>
  </div>
  He is the future founder of: <span class="fst-italic">&copy;Some Guy&trade;</span>
    <span class="fw-normal"> S/W Productions</span>
</div>



<div class="container-sm text-left col-6 mt-2">
  <p>TurboChat is a web application for hosting chat sessions.</p>
  <P>With it you can:</P>
  <li> join a chat room,</li>
  <li> create a new chat room,</li>
  <li> or chat privately with one other user.</li>
  <p class="mt-2">It is written in Ruby on Rails.  It uses Turbo, Stimulus, and Redis.</p>
</div>

app/views/pages/home.html.erb
<h1>Welcome to TurboChat</h1>

<% if current_user %>
  <h6>You are logged in as:  </h6>
  <%= image_tag(current_user.avatar_thumbnail) %> <%= current_user.username %><br>
  <%= link_to '  Start Chatting...', rooms_path,
      class: 'bi bi-chat-square-dots btn btn-secondary btn-lg mt-2' %>

<% else %>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary mt-2 btn-lg' %>
  <%= link_to '  Signup!', new_user_registration_path,
              class: 'bi bi-pen mt-2 btn btn-success btn-lg' %>
<% end %>