config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'pages#home'

  get 'about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # To support Devise for User management
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Routes for Rooms
  resources :rooms do
    resources :messages
  end

  get 'roomslist', to: 'rooms#list'
  get 'rooms_admin', to: 'rooms#admin'

  # Custom routes for users
  get 'user/:id', to: 'users#show', as: 'user'
end

app/models/room.rb
# frozen_string_literal: true

# Definition of the public and private chatrooms of this app
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  scope :private_rooms, -> { where(is_private: true) }
  after_create_commit { broadcast_if_public }
  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy

  def broadcast_if_public
    broadcast_append_to 'rooms' unless self.is_private
  end

  def self.create_private_room(users, room_name)
    current_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: current_room.id)
    end
    current_room
  end

  def participant?(room, user)
    room.participants.where(user: user).exists?
 #   Participant.where(user_id: user_id, room_id: room.id).exists?
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Controller for chat rooms
class RoomsController < ApplicationController
  #  The authenticate_user! method comes from Devise
  before_action :authenticate_user!, except: %i[list]
  before_action :set_status

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)

    render 'index'
  end

  def create
    @room = Room.create(whitelist_room_params)
  end

  def show
    @current_room = Room.find(params[:id])

    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new

    #  Using Pagy gem for pagination:
    #   1.  First variable, pagy_messages, comprises all messages in the room in descending order
    #   2.  When pagy is called, two variables are returned:  @pagy and the messages to display
    #   Since pagy_messages is in descending order, the second statement below returns the 20 most
    #   recent messages
    pagy_messages = @current_room.messages.order(created_at: :desc)
    @pagy, messages = pagy(pagy_messages, items: 20)
    #   3  Because we want to lopp through messages as message1, 2, 3, we have to reverse the order
    #      of "messages", above.  Put that reverse order in our @messages variable
    @messages = messages.reverse

    @users = User.all_except(current_user)

    render 'index'
  end

  def list
    @public_rooms = Room.public_rooms
  end

  def edit
    set_room
  end

  def update
    set_room
    if @room.update(whitelist_room_params)
      flash[:notice] = 'The Room was updated successfully.'
      redirect_to roomslist_path
    else
      # Error trapping
      # Re-render the "edit" page.
      # Because the save returned false, the error trapping on the "edit" page
      # will display the errors
      render 'edit', status: :unprocessable_entity
    end
  end

  def admin
    @public_rooms = Room.public_rooms
    @private_rooms = Room.private_rooms
    @participants = Participant.all
  end

  def destroy
    set_room

    if @room.destroy
      #
      # Generate a confirmation message for the user.
      flash[:notice] = 'The Room was deleted successfully.'

      redirect_to rooms_admin_path

    else

      # Error trapping
      # Re-render the "edit" article page.
      # Because the save returned false, the error trapping on the "edit" page
      # will display the errors
      render 'admin', status: :unprocessable_entity
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def whitelist_room_params
    params.require(:room).permit(:name, :description)
  end

  def set_status
    current_user&.update(status: User.statuses[:online])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_new_room.html.erb
<%= form_with(model: @room, remote: true, class: 'd-flex',
          data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset'}) do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/rooms/_room.html.erb
<div>
  <%= link_to room.name, room, data: {turbo: 'false'} %>
</div>

app/views/rooms/admin.html.erb
<h5>Rooms Administration </h5>
<h5 class="mt-2 bi bi-person-rolodex">  Current Public Rooms:</h5>
<div class="table-responsive">
  <table class="table table-bordered table-secondary w-auto">
    <thead>
      <tr class="table table-dark text-center">
        <th class="w-25">Name</th>
        <th class="w-25">Description</th>
        <th class="w-25">Message Count</th>
        <th class="w-25">Admin Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @public_rooms.each do |room| %>
        <tr>
          <td class="table-primary px-4"><%= link_to room.name, edit_room_path(room), class: "link-dark" %></td>
          <td class="table-primary px-4"><%= room.description %></td>
          <td class="table-primary px-4 text-center"><%= room.messages.count %></td>
          <td class="table-primary px-4 text-center">
            <%= link_to 'Delete', room_path(room),
                            class:"btn btn-warning",
                            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<% if @private_rooms %>
  <h5 class="mt-2 bi bi-person-rolodex">
    Current Private Rooms:
  </h5>
  <div class="table-responsive">
    <table class="table table-bordered table-secondary w-auto">
      <thead>
        <tr class="table table-dark text-center">
          <th class="w-25">Name</th>
          <th class="w-25">Participants</th>
          <th class="w-25">Message Count</th>
          <th class="w-25">Admin Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @private_rooms.each do |priv_room| %>
          <tr>
            <td class="table-primary px-4"><%= link_to priv_room.name, edit_room_path(priv_room), class: "link-dark" %></td>
            <td class="table-primary px-4">

              <% @participants.where(room_id: priv_room.id).each do |participant| %>
                <% user = User.find(participant.user_id) %>
                <%= user.username %>
              <% end %>

            </td>
            <td class="table-primary px-4 text-center"><%= priv_room.messages.count %></td>
            <td class="table-primary px-4 text-center">
              <%= link_to 'Delete', room_path(priv_room),
                              class:"btn btn-warning",
                              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container row justify-content-center col-12">

  <%= form_with(model: @room, local: true, class: 'shadow p-3 mb-3 mt-4 bg-grey rounded') do |f| %>
    <div class="form-group row">
      <%= f.label :name, "Room name:", class: "col-2 col-form-label" %>
      <div class="col-4">
        <%= f.text_field :name, class: "form-control shadow rounded" %>
      </div>
    </div>

    <div class="form-group row mt-2">
      <%= f.label :description, "Description:", class: "col-2 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :description, class: "form-control shadow rounded",
                          autocomplete: 'off',
                          placeholder: "Enter a description of room topic or participants" %>
      </div>
    </div>

    <div class="mt-2 text-center">
      <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/rooms/index.html+turbo_frame.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag(
                              "prepend",
                               target: "messages-container",
                               template: %(#{render @messages})
      )
  %>
  <%= turbo_stream_action_tag(
                              "replace",
                              target: "pager",
                              template: %(#{render "messages/pager", pagy: @pagy})
      )
  %>

<% end %>

app/views/rooms/index.html.erb
<h2>Chat Room Index</h2>

<%= turbo_frame_tag 'user_status_appearance_channel' %>
<div id='user_status_appearance_channel'></div>

<div id="chatroom_container" class="row bg-dark text-light">
  <div id="side_panel" class="col-md-4 col-sm-4">
    <h5 class="text-warning"> You:  </h5>
    <li class="list-group-item d-flex align-items-center justify-content-between
               user_list_item">
      <div class="status-icon-container">
        <%= link_to image_tag(current_user.chat_avatar, class: 'chat_profile_picture'),
                    current_user %>

        <%= turbo_stream_from 'user_status' %>

        <div>
          <%= render 'users/status', user: current_user %>
        </div>

      </div>

      <div class="ms-2 me-auto username">
        <%= current_user.username %>
      </div>

    </li>

    <h5 class="mt-2"> Users: </h5>
    <%= turbo_stream_from 'users' %>
    <div id="users">
      <%= render @users %>
    </div>

    <h5 class="mt-2"> Rooms: </h5>
    <%= render 'rooms/new_room' %>
    <%= turbo_stream_from 'rooms' %>
    <div id="rooms">
      <%= render @rooms %>
    </div>

  </div>

  <div id="room_container" class="col-md-8 col-sm-8 bg-dark text-light">

    <% if @current_room %>
      <div id="current_room">

        <h4 class="text-center"> <%= @user&.username || @current_room.name %> </h4>

        <%= turbo_stream_from @current_room %>

        <div id="messages" data-controller="scroll">
          <%= turbo_frame_tag "page_handler" %>
          <%= render "messages/pager", pagy: @pagy %>
          <div id="messages-container">
            <%= render @messages %>
          </div>
        </div>

        <%= render 'messages/new_message_form' %>

      </div>
    <% end %>
  </div>

</div>

app/views/rooms/list.html.erb
<h5 class="mt-2 bi bi-person-rolodex">  Current Rooms:</h5>
<div class="table-responsive">
  <table class="table table-bordered table-secondary w-auto">
    <thead>
      <tr class="table table-dark ">
        <th class="w-25">Name</th>
        <th class="w-25">Description</th>
      </tr>
    </thead>
    <tbody>
      <% @public_rooms.each do |room| %>
        <tr>
          <td class="table-primary px-4"><%= link_to room.name, edit_room_path(room), class: "link-dark" %></td>
          <td class="table-primary px-4"><%= room.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>