config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'pages#home'

  get 'about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # To support Devise for User management
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Routes for Rooms
  resources :rooms do
    resources :messages
  end

  get 'roomslist', to: 'rooms#list'
  get 'rooms_admin', to: 'rooms#admin'

  # Custom routes for users
  get 'user/:id', to: 'users#show', as: 'user'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">TurboChat</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Rooms List', roomslist_path, class: 'nav-link' %>
        </li>

        <% if current_user && !current_user.admin %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
              Your Profile
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Edit your profile', edit_user_registration_path(current_user),
                             class:"dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path,
                             method: :delete, data: { "turbo-method": :delete },
                             class:"dropdown-item" %>
              </li>
            </ul>
          </li>

        <% elsif current_user && current_user.admin %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
              Your Admin Profile
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Edit your profile', edit_user_registration_path(current_user),
                            class:"dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path,
                            method: :delete, data: { "turbo-method": :delete },
                            class:"dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to 'Rooms Administration', rooms_admin_path,
                            class:"dropdown-item" %>
              </li>
            </ul>
          </li>

        <% else %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
              Get Started
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Login', new_user_session_path, class:"dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Sign Up!', new_user_registration_path, class:"dropdown-item" %>
              </li>
            </ul>
          </li>

        <% end %>

        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>


      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <title>Turbochat</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- JavaScript Bundle with Popper -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">


    <style>
      <%= ".msg-#{current_user&.id}" %> {
        background-color: #007bff !important;
        padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end
      }
    </style>

  </head>

  <body>
    <div class="container">

      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          &#9757; <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          &#9757; <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% end %>

      <%= render 'layouts/navbar' %>

      <%= yield %>

    </div>

  </body>
</html>